version: 2
jobs:
  build:    
    docker:
      - image: docker
    environment:
      IMAGE_NAME: grindrodbank/pgmodeler-docker-x11
      PGMODELER_VERSION: v0.9.2-alpha1
    working_directory: ~/pgmodeler-docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - run: |
          cd container/docker 
          docker build -t $IMAGE_NAME:latest --build-arg PGMODELER_VERSION=$PGMODELER_VERSION .
  build-sh:    
      docker:
        - image: docker
      environment:
        IMAGE_NAME: grindrodbank/pgmodeler-docker-x11
        PGMODELER_VERSION: v0.9.2-alpha1
      working_directory: ~/pgmodeler-docker
      steps:
        - checkout
        - setup_remote_docker:
            docker_layer_caching: true
            version: 18.06.0-ce
        - run: |
            cd container 
            pwd
            ls
            ls -la
            ./build_multi.sh        
workflows:
  version: 2
  build-commit:
    jobs:
      - build
      - build-sh
              