version: 2
jobs:
  build:    
    docker:
      - image: docker
    environment:
      IMAGE_NAME: grindrodbank/pgmodeler-docker-x11
      PGMODELER_VERSION: v0.9.2-alpha1
    steps:
      - checkout
      - run: cd container/docker   
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest --build-arg PGMODELER_VERSION=$PGMODELER_VERSION .
workflows:
  version: 2
  build-commit:
    jobs:
      - build
              