version: 2
jobs:
  build:    
    docker:
      - image: docker
    environment:
      IMAGE_NAME: grindrodbank/pgmodeler
      PGMODELER_VERSION: v0.9.2-alpha1
    working_directory: ~/pgmodeler-docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # build and push Docker image to dockerhub.    
      - run: |
          TAG=$PGMODELER_VERSION
          cd container
          docker build -t $IMAGE_NAME:$TAG --build-arg PGMODELER_VERSION=$PGMODELER_VERSION --file=`pwd`/docker/Dockerfile .          
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push $IMAGE_NAME:$TAG
          # Tag and push latest
          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest          
workflows:
  version: 2
  build-commit:
    jobs:
      - build
              