FROM ubuntu:18.04
LABEL maintainer="Michael van Niekerk <mvniekerk@gmail.com>"

COPY --from="pgmodeler-docker-x11/build:${PGMODELER_VERSION}" /source/pgmodeler/dist/pgmodeler.tar.gz /opt/
WORKDIR /opt
RUN tar -xvzf pgmodeler.tar.gz; mv pgmodeler.tar.gz /pgmodeler.tar.gz; mv pgmodeler* pgmodeler
RUN apt-get update; apt-get install -y libxml2 libgl1 libpng16-16 libharfbuzz-gobject0 libqt5gui5 libpq5; apt-get clean
CMD /opt/pgmodeler/start-pgmodeler.sh